name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "main"

jobs:
    fail-job:
        runs-on: ubuntu-latest
        steps:
            - name: Fail step
              run: exit 1